language: python
python:
- '3.6'
install:
- pip install -r requirements-build.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: be034e2a-2581-45c1-b51c-ac8371f209d4
  app: quick-tutor-tf
  on:
    repo: uva-cs3240-s20/project-101-team-falcon
