# Generated by Django 3.0.2 on 2020-04-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill_out_sheet',
            name='no_response',
            field=models.BooleanField(default=True),
        ),
    ]
