# Generated by Django 3.0.2 on 2020-02-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200217_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='help_needed',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
