# Generated by Django 3.0.4 on 2020-04-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200410_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='help_needed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
