# Generated by Django 3.0.4 on 2020-04-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_fill_out_sheet_no_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill_out_sheet',
            name='has_tutor_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
