# Generated by Django 3.0.2 on 2020-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_help_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='activeTutor',
            field=models.BooleanField(default=False),
        ),
    ]
