# Generated by Django 3.0.2 on 2020-03-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200320_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user\\static\\user\\default.jpg', upload_to='profile_pics'),
        ),
    ]
