# Generated by Django 3.0.2 on 2020-03-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.TextField(blank=True, help_text='message content', max_length=400),
        ),
    ]
