# Generated by Django 3.0.2 on 2020-03-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200317_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.TextField(blank=True, max_length=400, verbose_name='message content'),
        ),
    ]
