# Generated by Django 3.0.4 on 2020-03-28 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20200322_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fill_Out_Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_desc', models.TextField(blank=True, max_length=100)),
                ('help_desc', models.TextField(blank=True, max_length=500)),
                ('time_slot', models.TextField(blank=True, max_length=50)),
                ('meeting_place', models.TextField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
