# Generated by Django 3.0.4 on 2020-03-28 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_fill_out_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='class_desc',
        ),
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='help_desc',
        ),
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='meeting_place',
        ),
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='user',
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
