# Generated by Django 3.0.4 on 2020-03-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200328_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='name',
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='class_desc',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='help_desc',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='time_slot',
            field=models.CharField(choices=[('1', '5-15 minutes'), ('2', '15-30 minutes'), ('3', '30 minutes-1 hour'), ('4', 'More than 1 hour')], default='1', max_length=20),
        ),
    ]
