# Generated by Django 3.0.4 on 2020-03-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200328_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill_out_sheet',
            name='computing_ID',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='meeting_places',
            field=models.CharField(choices=[('1', 'Alderman Library'), ('2', 'Clark (Brown) Library'), ('3', 'Clemmons Library'), ('4', 'Starbucks (Corner)'), ('5', 'Starbucks (Newcomb)'), ('6', 'Argo Tea'), ('7', 'Einstein Bros (Rice)'), ('8', '15|15')], default='1', max_length=40),
        ),
    ]
