# Generated by Django 3.0.4 on 2020-03-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200328_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill_out_sheet',
            name='tutor_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
