# Generated by Django 3.0.4 on 2020-03-28 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0012_fill_out_sheet_tutor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='computing_ID',
        ),
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='tutor_name',
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
