# Generated by Django 3.0.4 on 2020-03-29 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_auto_20200328_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='receiver',
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='receiver',
            field=models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='sender',
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='sender',
            field=models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
