# Generated by Django 3.0.4 on 2020-03-29 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0014_auto_20200328_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='receiver',
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='receiver',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='sender',
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='sender',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
