# Generated by Django 3.0.4 on 2020-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200328_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill_out_sheet',
            name='has_tutor_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fill_out_sheet',
            name='has_tutor_rejected',
            field=models.BooleanField(default=True),
        ),
    ]
