# Generated by Django 3.0.4 on 2020-03-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200329_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fill_out_sheet',
            name='meeting_places',
        ),
    ]
