# Generated by Django 3.0.4 on 2020-03-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_fill_out_sheet_meeting_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='fill_out_sheet',
            name='meeting_places',
            field=models.CharField(choices=[('Alderman Library', 'Alderman Library'), ('Clark (Brown) Library', 'Clark (Brown) Library'), ('Clemmons Library', 'Clemmons Library'), ('Starbucks (Corner)', 'Starbucks (Corner)'), ('Starbucks (Newcomb)', 'Starbucks (Newcomb)'), ('Argo Tea', 'Argo Tea'), ('Einstein Bros (Rice)', 'Einstein Bros (Rice)'), ('15|15', '15|15')], default='15|15', max_length=200),
        ),
    ]
